### ISSUE TITLE
bug with thaumcraft armor

### ISSUE THREAD

**Issue by touhouzun** [pau101/Wings#11]
forge:14.23.5.2776
mods:
![default](https://user-images.githubusercontent.com/31458903/49056603-55b74f80-f237-11e8-92ba-5d02ef206ad9.PNG)
issue
![2018-11-27_11 26 57](https://user-images.githubusercontent.com/31458903/49056654-8d25fc00-f237-11e8-80e6-be82200f5fe4.png)
![2018-11-27_11 27 21](https://user-images.githubusercontent.com/31458903/49056671-a62ead00-f237-11e8-989d-e38c6f4b997a.png)
![2018-11-27_11 27 26](https://user-images.githubusercontent.com/31458903/49056675-a7f87080-f237-11e8-803f-2f5669f6c735.png)
![2018-11-27_11 27 46](https://user-images.githubusercontent.com/31458903/49056676-a9c23400-f237-11e8-9152-16fa1373f38d.png)
Wings works fine with botania/astral sorcery's armors,but not thaumcraft's.

**Comment by pau101** [comment]
Thanks for the report! Thaumcraft will need to correct their armor implementation as I can't do anything on my side.

**Comment by touhouzun** [comment]
_(:з)∠)_

**Comment by touhouzun** [comment]
Well...Thaumcraft was uncontinued, I don't want your project unfinished, Mr.(?)@pau101 
It's already year 2020, and may you have a nice year.
The issue won't be fixed, forever._ (:з)∠) _
