### ISSUE TITLE
JEI Dependency

### ISSUE THREAD

**Issue by NillerMedDild** [pau101/Wings#13]
Hello o/

Would you consider making JEI a soft dependency? I don't think leaving out JEI would cause issues.
In addition, Wings does not accept the latest JEI version.

**Comment by pau101** [comment]
JEI is an optional dependency, however I specify the version range that will be supported according to JEI's major release to avoid random crashes during play from API changes. For each new major JEI release I check if I can extend Wing's supported JEI version range or begin a new supported range. I've just released [Wings 1.1.1](https://minecraft.curseforge.com/projects/wings/files/2645444) to extend the range to 14.
