### ISSUE TITLE
Nasty world-breaking crash when a pair of wings is put onto a Dawnstone Anvil from Embers Rekindled

### ISSUE THREAD

**Issue by Febilian** [pau101/Wings#14]
https://gist.github.com/Febilian/4368f54b8a9d69bd02738bb4f3e027c7

This happened on a dedicated server, and as soon as it happened, the server just consistently crashed on startup until Wings was removed.

**Comment by pau101** [comment]
Thanks for the report! You'll want to report this to Embers Rekindled as they are performing an invalid operation by offering an empty item stack as an ingredient to repair, a situation that never occurs in vanilla code.

I would also suggest they reorder this [expression](https://github.com/EpicSquid/Embers/blob/604289f306c1bb67f0c53807a0497dd95c42d403/src/main/java/teamroots/embers/recipe/AnvilRepairRecipe.java#L15) such that the blacklist check guards the `isRepairable` call so it can be functional for temporary error fixes such for this.

I however will adjust my ore dictionary logic as I should be handling arbitrary empty stacks.

**Comment by pau101** [comment]
[Wings 1.1.2](https://minecraft.curseforge.com/projects/wings/files/2648560) is now out with the patch.
