### ISSUE TITLE
Wings-related server crash?

### ISSUE THREAD

**Issue by Luke616** [pau101/Wings#21]
Getting this crash with wings installed, when removing the mod the server loads up fine. Seems like its related to a mixin issue? The client loads up okay, its seems to just be a server issue. Might be related to https://github.com/iLexiconn/LLibrary/issues/117

This is what the server spat out:
https://pastebin.com/TUvXWfML

This is what the log file says:
https://pastebin.com/Fz79az4S

Versions:
Minecraft 1.12.2
Forge 14.23.5.2796
LLibrary 1.7.17
Wings 1.1.2

Thanks for any insight you could offer as to what's happening!

**Comment by pau101** [comment]
Thanks for the report! This was fixed in LLibrary 1.7.18.
