### ISSUE TITLE
Valkyrien Warfare incompatibility

### ISSUE THREAD

**Issue by enderplayer2001** [pau101/Wings#22]
After careful testing, i discovered that Wings and Valkyrien Warfare cause a pre-loading crash. There is no crash report, the game window doesn't open and this shows up on the latest log:

12:28:20	mixin	main	Mixin prepare failed preparing entity.MixinEntityIntrinsic in mixins.valkyrienwarfare.json: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException Critical problem: mixins.valkyrienwarfare.json:entity.MixinEntityIntrinsic target net.minecraft.entity.Entity was already transformed.
org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: mixins.valkyrienwarfare.json:entity.MixinEntityIntrinsic target net.minecraft.entity.Entity was already transformed.
at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargets(MixinInfo.java:885)
at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:856)
(...)

below goes the full log.
[latest.log](https://github.com/pau101/Wings/files/2727353/latest.log)

i've also warned the creator of Valkyrien Warfare of this issue.

**Comment by pau101** [comment]
Pardon my late reply, but incompatibility issues are no longer resolved for 1.12
