### ISSUE TITLE
logout and login again in the fly mode will make fly become creative mode's fly

### ISSUE THREAD

**Issue by Jecvay** [pau101/Wings#23]
logout and login again in the flying mode
will make fly become creative mode's fly ( can suspend in sky )

and if player teleport to another world, the fly status will become normal.

**Comment by Jecvay** [comment]
spongeforge server
mc 1.12.2

**Comment by pau101** [comment]
Thanks for the report! I've tested with SpongeForge 1.12.2-2768-7.1.5 and I cannot reproduce this issue.

**Comment by Laike-Endaril** [comment]
Could not reproduce in normal forge stable release (14.23.5.2768)

**Comment by LemADEC** [comment]
No details provided, not reproductible => close?

**Comment by Jecvay** [comment]
sorry ,  this is not a bug. just want the speed of spint can be configured
