### ISSUE TITLE
Wings with Llibrary 1.7.17

### ISSUE THREAD

**Issue by MattmonGaming** [pau101/Wings#25]
This mod does not appear to be compatible with version 1.7.17 of llibrary on a forge server (it does work client side). If you do use the most up to date versions of these mods, your server will crash depending on what other mods are present (the list is quite long). Unfortunately, version 1.7.17 of llibrary is needed for any more up-to-date versions of forge. I hope this can be resolved soon.

I can get a lot more specific if needed, but the issue is VERY easy to recreate.

**Comment by pau101** [comment]
Thanks for reporting! This is a known LLibrary issue which was fixed in 1.7.18.
