### ISSUE TITLE
Ores config is ignored (wings-1.1.3-1.12.2)

### ISSUE THREAD

**Issue by nickjackson-ff** [pau101/Wings#27]
The settings for amethyst and fairy dust ores are being ignored with Wings 1.1.3 (MC 1.12.2).

It could be related to this commit: https://github.com/pau101/Wings/commit/046395dfcfde21bb69c77d3d3268565386f809ab

If the file doesn't exist, ores.cfg is created, but as follows:
```
# Configuration file

amethyst {
}


fairy_dust {
}
```

Thanks for all your amazing work!

**Comment by AdaraChristine** [comment]
Im having the same problem.
Here is my config settings
```fairy_dust {
    I:count=1
    I:maxHeight=24
    I:minHeight=0
    I:size=4
```
Spawn result
![2019-03-25_16 03 16](https://user-images.githubusercontent.com/30163566/54959861-b6ba1000-4f17-11e9-942f-6baeb70b81ef.png)

**Comment by pau101** [comment]
Thanks for the report! I'll get a new release out soon.

**Comment by pau101** [comment]
[Wings 1.1.4](https://minecraft.curseforge.com/projects/wings/files/2692819) is now out!

**Comment by AdaraChristine** [comment]
Thank you for your hard work on an awesome mod!

**Comment by pau101** [comment]
Glad you are enjoying it!
