### ISSUE TITLE
Problem with spongeforge

### ISSUE THREAD

**Issue by Azvalk** [pau101/Wings#3]
Hi ^^
Super mod, I am in total admiration +.+
but.. little problem..
Here is what happens when the mod is used on a server forge 2705, with the sponge currently recommended. ( spongeforge-1.12.2-2705-7.1.0-BETA-3361 )

[latest.log](https://github.com/pau101/Wings/files/2368118/latest.log)

This doesn't happen when there isn't the Sponge, but I need it.. so.. solution ?

**Comment by Azvalk** [comment]
This thing, solved the problem, Sponge goes first.
https://forums.spongepowered.org/t/spongebootstrap-fixes-ordering-issue-with-other-coremods/12275
But .. it broke something else, much more fundamental ..
I saw an error speaking of player interaction, when I wanted to consume food, vanilla. So, no, it's not a solution I can accept.
But that proves that there is a problem with the loading order of the mod ^^

**Comment by pau101** [comment]
Thanks for the report! I've identified the cause and a new release will be soon.

**Comment by pau101** [comment]
[Wings 1.0.5](https://minecraft.curseforge.com/projects/wings/files/2616309) is now out.

**Comment by Azvalk** [comment]
It works: D
The mod and SpongeForge do not cause more crash.
But the problem I had while testing SpongeBootstrap occurs again.
I am not good at reading and understanding errors, and these mention several mod of my modpack, so I will test by removing some of them, but I already give the first line of error ..

```
[Server thread / ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$RightClickBlock@13afdc1b:
kotlin.KotlinNullPointerException: null
```

It happens when you try to consume an item, such as a steak.
