### ISSUE TITLE
 Incompatibility with Galacticraft

### ISSUE THREAD

**Issue by Jannik24** [pau101/Wings#31]
If I have Galacticraft in it then what happens in the screenshot is shown when I take it out then does not happen then it's all normal

- Forge Version = 1.12.2-forge1.12.2-14.23.5.2838
- Wings Version = wings-1.1.4-1.12.2
- Galacticraft Version = Core + Planets + MicdoodleCore
- Core Version = GalacticraftCore-1.12.2-4.0.2.210
- Planets Version = Galacticraft-Planets-1.12.2-4.0.2.210
- MicdoodleCore Version = MicdoodleCore-1.12.2-4.0.2.210
**Results**
- mit Galacticraft = Player unter Cursor 
![2019-05-31_12 27 24](https://user-images.githubusercontent.com/37809734/58700177-ac951180-839f-11e9-897a-853062c9d3e7.png)

- ohne Galacticraft = Player befindet sich im Cursor
![2019-05-31_12 51 16](https://user-images.githubusercontent.com/37809734/58701386-09de9200-83a3-11e9-9429-e4a7ff69d291.png)

**Comment by Jannik24** [comment]
with Galacticraft = Player under Cursor
without Galacticraft = Player is in the Cursor

**Comment by pau101** [comment]
Sorry for my late reply, but I will not be resolving incompatibility reports for 1.12 any longer.
