### ISSUE TITLE
Bug/Crash Wings seems to crash repetitively on single player and mostly servers.

### ISSUE THREAD

**Issue by SirAron111** [pau101/Wings#39]
Bug/Crash Wings seems to crash repetitively on single player and mostly servers.

I loaded up my world I made and suddenly the game starts crashing on me I played for a few hours yesterday no problem now it sometimes crashes on loading wings mod.

Some players of my modpack also have the same problem here are some crash logs all pointing to the same problem. of some mobends_wings part.

Wings 1.1.5 for Minecraft 1.12.2
MC 1.12.2
Forge 14.23.5.2838

https://pastebin.com/MXm76WCV
https://pastebin.com/GPuTviCX
https://pastebin.com/ymux3ma1
https://pastebin.com/21t46DUn
https://pastebin.com/FVzvEy6v
https://pastebin.com/FB3D2XN3

**Comment by pau101** [comment]
Thanks for reporting! These crash reports don't show any indication of Wings being the culprit, unfortunately.

**Comment by SirAron111** [comment]
but they all stop at this 

None                                     |
    | LCHIJA | teslacorelib_registries           | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                   | None                                     |
    | LCHIJA | unidict                           | 1.12.2-2.9.2             | UniDict-1.12.2-2.9.2.jar                           | None                                     |
    **| UD     | mobends_wings                     | 1.0.0                    | wings-1.1.5-1.12.2.jar                             | None**

**Comment by pau101** [comment]
That part of the crash report is showing all the mods, and "mobends_wings" is an internal mod conditionally loaded if Mo' Bends is also installed. "UD" indicates it is unloaded and disabled.

**Comment by pau101** [comment]
When you say "it never happens" which crash report are you referring to? It is difficult for me to diagnose a potential issue with numerous varying reports.

**Comment by SirAron111** [comment]
Since all I did was update the pack adding the wings mod I thought it could have been this.

I am not the best at finding out certain things from these reports it just never happened to me that I got so many crash reports that all only showed one common thing and that was the DU wings thingy. And if I got multiple reports in the past t and they showed something common it was mostly the cause.

If you say its not than it has to be something else.

I changed a few things around and made some fixes and updated the beta version of my pack now I will see if I get some new crash reports.

But thx for the help. I will keep investigating this issue on my end if it stops its good. If not I will maybe be back XD

**Comment by pau101** [comment]
I did provide a comment on the Astral Sorcery issue you submitted the other day and it appears it will be fixed soon.

The statuses of mods in the crash report are significant if you see "E" in it, indicating a load error. Just before the table there is a description:
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

I'm closing this as I do not see any causality concerning Wings.
