### ISSUE TITLE
PLS HELP, Wings not rendering

### ISSUE THREAD

**Issue by Herbertofury** [pau101/Wings#43]
Its highly unlikely you will be able to help me figure this out but it would be much appreciated. 
with galaticraft installed wings no longer render and it is only the case when metamorph is installed. I have been doing some testing and running several different instances with mcedit and regular minecraft. Each have only these exact mods installed. I have been trying different versions and mod setups and config settings to no avail. $ reward if someone can help me figure this out (=.

minecraft version 1.12.2
metamorph version 1.18
mclib version 1.0.3
wings version 1.15
Galacticraft version: 
GalacticraftCore-1.12.2-4.0.2.237
Galacticraft-Planets-1.12.2-4.0.2.237
MicdoodleCore-1.12.2-4.0.2.237
forge version: 14.23.5.2846

**Comment by radfast** [comment]
It's not a Wings issue, the issue is caused somehow by Metamorph and BlockBuster mods (Metamorph is a BlockBuster dependency) so that `me.paulf.wings.client.renderer.LayerWings` (and similar layers added by other mods) is missing from the LayerRenderers.

**Comment by pau101** [comment]
Thanks for reporting!

Unfortunately it is difficult to ensure compatibility with mods replacing the player renderer such as Metamoprh. As such there is little I can do on my end.
