### ISSUE TITLE
[Suggestion] Config option to disable Amethyst Ore gen

### ISSUE THREAD

**Issue by katubug** [pau101/Wings#44]
I have a bunch of mods now that add various Amethyst ores. I love that your recipes use the OreDictionary, but I would like to be able to disable the generation of the ore, if possible.

**Comment by pau101** [comment]
Thanks for the suggestion! Luckily the current config does allow for completely removing ore generation. Inside "config/wings/ores.cfg" the count can be set to 0, by default amethyst is 2.

**Comment by katubug** [comment]
Wow, I am a big old dingus who should not do her configs when she is sleep deprived! lol I completely missed that file. Thank you very much for your kind and timely response, and I apologize for my mistake!
