### ISSUE TITLE
Animation Glitches when Flying not in 1st POV

### ISSUE THREAD

**Issue by PhoebeJones** [pau101/Wings#45]
![2019-09-28_14 29 04](https://user-images.githubusercontent.com/55931760/65823235-5f1e9900-e207-11e9-82f6-54163aaad8f8.png)
![2019-09-28_14 36 15](https://user-images.githubusercontent.com/55931760/65823236-5f1e9900-e207-11e9-9c1c-0b4bc6806592.png)

Glitches when not in 1st POV and wings in Bauble chest slot:

- TAN water bar has background darkened

- When flying, no wings are present and you fly upside-down. You do, however, do the pose with the arms. 

If you press R for controlled descent or just walk around, and not in 1st POV, everything but the TAN water bar is normal. 

When in 1st POV, everything is fine (TAN water bar included). I haven't tested on a server with friends so don't know if it does animate properly but otherwise everything works fine.

I tried updating the library, Baubles, and Forge.

I'm new to modpacks so I'm embarrassed about how probably really messy this first modpack is and I don't even realize it.

I don't have mo'bends installed.

**Comment by PhoebeJones** [comment]
Update: same issues for when wings are in vanilla chest slot. Additionally, this issue is with any of the wings.

**Comment by pau101** [comment]
Thanks for reporting! Can you provide me a link to the modpack or the list of mods? There must be a conflict somewhere.

**Comment by PhoebeJones** [comment]
Bit of warning, this is the list of mods from my experimental modpack. This is mostly just a level or two above putting every mod that seemed interesting together in MultiMC and then me trying to learn how to fix it so it can work.

I had a hunch, tested it, and found something! If I remove Ido 1.0.4, the glitches change. All glitches but the TAN water bar being darkened when standing with wings while not in 1st POV are gone. The wings are there, animated, and I'm not upside-down. The TAN water bar glitch is not seen during flying or controlled landing now, just standing. The TAN water bar glitch was only seen after Wings was added (I play-tested before adding Wings) so something must still be up. 

Also, there are unfortunately a lot of mods that I jammed in. Around 138. (Damage Control is not enabled.) Um.. sorry.

![1](https://user-images.githubusercontent.com/55931760/65824488-0a871800-e21f-11e9-93e7-2807d89f410d.JPG)
![2](https://user-images.githubusercontent.com/55931760/65824489-0a871800-e21f-11e9-8438-802c29bcd36e.JPG)
![3](https://user-images.githubusercontent.com/55931760/65824490-0a871800-e21f-11e9-8536-18e03febc027.JPG)
![4](https://user-images.githubusercontent.com/55931760/65824491-0a871800-e21f-11e9-9703-63ba53fe0c9f.JPG)
![5](https://user-images.githubusercontent.com/55931760/65824492-0a871800-e21f-11e9-9635-b3b6f8689033.JPG)
![6](https://user-images.githubusercontent.com/55931760/65824493-0a871800-e21f-11e9-80e9-93fc12e182c7.JPG)

**Comment by PhoebeJones** [comment]
I just checked and I was mistaken. I disabled Wings and created a new world and the TAN water bar glitch was there. I'll need to backtrack to find who that issue belongs to.

**Comment by llazzllo** [comment]
It's Ido. I've only just made the author aware of the problem, and they suggested I make you aware of it, too. It appears that you are already aware of the problem. :)  I tested it with Wings and Ido as the only mods, and they are the ones conflicting.

**Comment by pau101** [comment]
Thanks for the help in looking into this! It appears Ido has faulty logic for determining when to intercept player rendering. There's nothing on my end I can do about this unfortunately.
