### ISSUE TITLE
Not compatible with craftbukkit based forge mod server

### ISSUE THREAD

**Issue by Chering031** [pau101/Wings#48]
This problem occurs on CatServer and Kettle
https://github.com/Luohuayu/CatServer/issues/72

What is ASM?

Is it not compatible if the bukkit creator doesn't fix it?

**Comment by pau101** [comment]
CatServer violates the licenses of all the projects for which it is built off of and consequently unsupported by me as well as the Forge team. You will find most significant mods will not run successfully on CatServer. I recommend enjoying Wings with a [Sponge](https://www.spongepowered.org/) server for play with plugins and mods.

**Comment by Chering031** [comment]
Thanks
