### ISSUE TITLE
hunger drain when flying with wings is a bit too fast

### ISSUE THREAD

**Issue by touhouzun** [pau101/Wings#49]
Just as the title, natural regeneration most quickly drains hunger, but wing-flying is the second. 

There's no config options to change hunger drain per tick when flying. 

It should may only a little faster than vanilla running/spriting, but not as fast as current "wings" version.

wings-1.1.6-1.12.2

**Comment by pau101** [comment]
Thanks for reporting!

The intention is you eat frequently while flying to keep hunger up. If this is not desired there is in fact a config for it. Inside of `config\wings\items.cfg` the "flyingExertion" and "landingExertion" can be set to 0 to disable or just decreased.

**Comment by touhouzun** [comment]
Found and worked, thanks!
At first I thought "flyingExertion" was meant to change wings' durability cost and not player's hunger cost._(:з)∠)_
Anyway, have a nice day!
