### ISSUE TITLE
Crash When installed with Mod "ElecCore"

### ISSUE THREAD

**Issue by Water-Moon** [pau101/Wings#5]
When I install this mod, it's library(LLibrary), and Eleccore together, the game crashed while initializing.
When I only install LLibrary and Eleccore, the game does not crash.
There seems to be a bug existing in mod Eleccore, but I still post this here so that you might have a chance of finding out what's going wrong and fix it.
(It seems that the conflict happens when the mod Eleccore is trying to register to FML)
The mod ElecCore is at this link:  https://github.com/Elecs-Mods/ElecCore

The attachments are the crash report and the latest log.
[latest.log](https://github.com/pau101/Wings/files/2381049/latest.log)
[crash-2018-09-14_05.28.49-client.txt](https://github.com/pau101/Wings/files/2381050/crash-2018-09-14_05.28.49-client.txt)

**Comment by pau101** [comment]
Thanks for the report! I checked out what `ElecCore` is doing, and it is at fault, you'll need to report to them.

**Comment by Water-Moon** [comment]
I've also sent an issue report to the ElecCore mod page, and I hope they will fix this wired thing.

**Comment by Water-Moon** [comment]
The author of mod ElecCore still does not reply to the issue...

**Comment by pau101** [comment]
Pardon my delayed response, but yes it appears the owner hasn't been active for a bit. I'll try contacting them to get this issue resolved.

**Comment by Water-Moon** [comment]
The problem no longer exists...
Thanks!
