### ISSUE TITLE
wings are invisble 

### ISSUE THREAD

**Issue by JoThePro23** [pau101/Wings#50]
the wings are invisible whenever i install this mod with it https://www.patreon.com/dragonsmod
if u have solutions plz tell me

**Comment by MermaidEva** [comment]
Hi, 

It looks like the Wings mod is incompatible with DragonFire - we have also run into this issue, I do not think there is a solution at this stage :( Perhaps in the future there will be considering the momentum the dragons mod is gaining in popularity!

**Comment by pau101** [comment]
Thanks for reporting and pardon my late response, but this is an error on their part. I cannot solve other mods not accounting for mod added player model layers.
