### ISSUE TITLE
bauble charm (and any) aren't in correct position when flying

### ISSUE THREAD

**Issue by touhouzun** [pau101/Wings#51]
wing 1.12.2 1.1.6
botania r1.10-363
![2020-02-14_12 45 48](https://user-images.githubusercontent.com/31458903/74502427-71843f80-4f28-11ea-9173-f0bddfea6b8e.png)
![2020-02-14_12 45 55](https://user-images.githubusercontent.com/31458903/74502428-734e0300-4f28-11ea-9954-426f23807c1b.png)
![2020-02-14_12 46 06](https://user-images.githubusercontent.com/31458903/74502431-75b05d00-4f28-11ea-929e-e481e41525e7.png)
![2020-02-14_12 46 12](https://user-images.githubusercontent.com/31458903/74502433-7648f380-4f28-11ea-9d9d-c95c4dee4bb8.png)
![2020-02-14_12 46 27](https://user-images.githubusercontent.com/31458903/74502436-7812b700-4f28-11ea-8aba-16b6ec011d6e.png)
![2020-02-14_12 46 39](https://user-images.githubusercontent.com/31458903/74502437-7943e400-4f28-11ea-9ffa-79c47cea1b57.png)
![2020-02-14_12 47 00](https://user-images.githubusercontent.com/31458903/74502441-79dc7a80-4f28-11ea-8a50-8c3aa2e8e2f7.png)
![2020-02-14_12 47 08](https://user-images.githubusercontent.com/31458903/74502445-7b0da780-4f28-11ea-8c63-26db61f2a451.png)
![2020-02-14_12 52 36](https://user-images.githubusercontent.com/31458903/74502658-274f8e00-4f29-11ea-8752-a9e51b4061db.png)
![2020-02-14_12 52 52](https://user-images.githubusercontent.com/31458903/74502661-29b1e800-4f29-11ea-908c-46a4b8179b69.png)

**Comment by Water-Moon** [comment]
Just personal opinion, but botania did not actually make the bauble render with 'relative position' on player. Instead they make them appear on a fixed place according to player orientation. Thus when this mod (Wings) change the player head position, the baubles would show in an incorrect and sometime funky location (which was actually the position of the player 'head' as the program reads it but not visually)... Looks might be hard to fix besides using some core modding...?

**Comment by pau101** [comment]
Yep, this isn't an error with my mod. You see this from Botania if you fly with the vanilla elytra.

**Comment by touhouzun** [comment]
> Yep, this isn't an error with my mod. You see this from Botania if you fly with the vanilla elytra.

What a pity. It has been months since I realized that vazkii had already dropped support for Botania 1.12.2 :(
