### ISSUE TITLE
wings 1.1.6 weird visual glitch 

### ISSUE THREAD

**Issue by Sageking10** [pau101/Wings#53]
![2020-02-25_21 19 18](https://user-images.githubusercontent.com/48606472/75305625-a3dd4900-5814-11ea-87f0-9a8e80806098.png)

This is the result of flying with the dragon wings.
Tested with other wings.

**Comment by Cryoraven** [comment]
i found that if you have JJ Races mod it prevents the wings from rendering

**Comment by maximogta** [comment]
Same problem here

**Comment by pau101** [comment]
Incompatibility issues will not be resolved for 1.12, and in this case Ido is at fault.
