### ISSUE TITLE
stops working in worlds

### ISSUE THREAD

**Issue by tuxedocat123** [pau101/Wings#57]
i will be playing a world and i get the wings a fly for a few min and they cut of and only let me float down and when i press r again they wont fly

**Comment by Water-Moon** [comment]
Well, maybe you could check your hunger/saturation? The wings won't let you fly unless you have a minimum hunger level (which can be adjusted in the configuration file).
By the way, under default setting, the consumption of hunger/saturation is rapid when flying, so be sure to check your hunger bar often :)
If this doesn't solve problem, maybe share screenshot/logs?

_Disclaimer: I'm not an official maintainer/author of the mod._

**Comment by tuxedocat123** [comment]
> Well, maybe you could check your hunger/saturation? The wings won't let you fly unless you have a minimum hunger level (which can be adjusted in the configuration file).
> By the way, under default setting, the consumption of hunger/saturation is rapid when flying, so be sure to check your hunger bar often :)
> If this doesn't solve problem, maybe share screenshot/logs?
> 
> _Disclaimer: I'm not an official maintainer/author of the mod._

hey it worked  i was on a survival world and my hunger was down to 2 bars but i was in creative so i thought it was fine but thanks for letting me know now it works thanks so much :)
