### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by KamiSami** [pau101/Wings#6]
While holding shift when flying will make your character fly forward towards the horizons, this would help to navigate the lands by looking down without actually going down, as currently it is hard to look the lands below you as you have to fly down and fly back up again.

**Comment by pau101** [comment]
For this behavior I did specifically fine tune the player's inclination required for horizontal travel to allow land to be reasonably viewed without vertical descent. If a more declined viewing angle is desired, I see the player having to be conscious of flight serving to help balance the mod. I do appreciate the feedback and hope this clarifies the current design.
