### ISSUE TITLE
Wings are invisible when running DragonFire Mod

### ISSUE THREAD

**Issue by MermaidEva** [pau101/Wings#64]
It seems as if the DragonFire mod created by Tiny Turtle is perhaps incompatible with Wings (or vice versa) as when we wear the wings with that mod active they are invisible altogether. Does anyone know of a workaround or fix? Thank you.

**Comment by pau101** [comment]
Thanks for reporting! Unfortunately, it is out of my control if a another mod changes player rendering in such a way which remove my wings. It will need to be reported to them.
