### ISSUE TITLE
Compatibility with Custom Player Models

### ISSUE THREAD

**Issue by SYMA-24G** [pau101/Wings#66]
While there are no game breaking bugs from loading both mods at the same time. The problem is when ever the player body/torso moves as a result of CPM, the wings stay still. I wanted my character to bob and sway as he walks, and to lean forward as he runs, etc, but the wings do not reflect these movements. Other than this it works fine, the arms still move forward in flight, and the whole player model does rotate as intended. I do not have much hope that something can be done to fix this, but I do not think it can hurt to ask.
Link to CPM:
https://github.com/Gamepiaynmo/CustomModel/tree/master

![ezgif com-gif-maker](https://user-images.githubusercontent.com/10476254/95693225-3e01ce00-0bf9-11eb-8427-532f020a5af3.gif)

**Comment by pau101** [comment]
Thanks for reporting! However, new integration will not be created for 1.12 as it is no longer supported.
