### ISSUE TITLE
[Suggestion] Make stats of wings an NBT tag or similar so that a set of wings could be improved

### ISSUE THREAD

**Issue by Goldenlion5648** [pau101/Wings#7]
I think it cold be cool to make each set of wings improvable. So each set could start with the same stats, but the player could add an upgrade to increase stats(could be done by pack makers, doesn't need new item). So the player could decrease the amount of hunger used.

**Comment by pau101** [comment]
Great suggestion, with it however, needs consideration for how "upgrades" play into the theme. Wings is not a technology mod and as such the wings items are more so physically altering the player. So, something like exhaustion variability would be bound to the player themselves. The wings are also only currently items and they will be obtained through spells from faries in the future. I would want to hold off on progressional mechanics until this change is introduced. Of course in the meantime open to ideas.
