### ISSUE TITLE
Wings don't follow model-tweaking mods

### ISSUE THREAD

**Issue by estradus** [pau101/Wings#70]
When used with mods that tweak the model (like mo'bends) the wings remain floating in place just behind my back and do not move with it.  Some mods that add these features do not follow the model, but some do.  Asking on Mo'Bends, they directed me to this update to the wearable backpacks mod which provided a solution to this problem.  https://github.com/copygirl/WearableBackpacks/pull/82

Combining these beautifully animated wings with the great animations of mo'bends would be an incredible experience and I hope it can be accomplished.

**Comment by pau101** [comment]
There is Mo' Bends integration implemented. The recent "beta" releases are not supported as Wings is not receiving any more 1.12 updates.
