### ISSUE TITLE
Issue - the wings disappear, when I click R

### ISSUE THREAD

**Issue by TaiSutcliff** [pau101/Wings#71]
Hi!
I have an issue about the wings. They are visible and their animation works when I'm standing normaly, but when I'm clicking R (which is not in conflict with anything) the wings disappear and my character is upside down. As soon as I turn the flying off, everything goes back to normal. I don't know how to fix this, can you help me?

**Comment by KreloX** [comment]
Hi,
I had the same issue as you today, but i quickly found why. For me it was causing the Idō mod, just removed it and it went fine.

**Comment by TaiSutcliff** [comment]
> Hi,
> I had the same issue as you today, but i quickly found why. For me it was causing the Idō mod, just removed it and it went fine.

If you don't mind me asking, what's an Idō mod?

**Comment by TaiSutcliff** [comment]
Oh! It's about the swimming! I'll check it out, thank you!

**Comment by KreloX** [comment]
It is a mod that adds similar crawling and swimming animations to those in 1.13 and above.

**Comment by pau101** [comment]
Yes the Ido mod is incompatible on their end.
