### ISSUE TITLE
How do you download the mod?

### ISSUE THREAD

**Issue by The-WingDinger** [pau101/Wings#77]
I am very confused on where to download the 1.16 version of this mod.

**Comment by Codename-Ps** [comment]
you have to compile it yourself but i have no idea how

**Comment by RavioliWpesto** [comment]
yea I kinda want help for this too plz

**Comment by RavioliWpesto** [comment]
> 
> 
> > I am very confused on where to download the 1.16 version of this mod.
> 
> There isnt a 1.16 version yet. Its in progress

I'm pretty sure there's a way to download the 1.16 version, I'm just not completely sure how it works

**Comment by LordGriefington** [comment]
it's a open sorce code, went to the main "wings" section on github, (or if you on to the forge page click on source and it will lead you there) click the green button called "code" and "download ZIP".
Warning: it's the version where they are working on, it's unfinished, it may not work very well and you have to compile it yourself.
My advice, wait for the release.

**Comment by pau101** [comment]
The 1.16 release is not completed yet as it has some final reworks to go. It should be soon.
