### ISSUE TITLE
No Textures?

### ISSUE THREAD

**Issue by EvilEclipse** [pau101/Wings#9]
Okay when im using the wings it flies obviously but theres no textures?

![2018-10-28_10 59 38](https://user-images.githubusercontent.com/44538218/47611444-9db04e80-daa0-11e8-8c9f-aa31da4478b1.png)

**Comment by jackthepanda04** [comment]
This happened to Joey Graceffa with the angel wings i think they were....maybe it could be other mods that are disturbing it.try using just the mod along with the required ones and see or if not maybe one you need a newer version of one of the required mods.

**Comment by jackthepanda04** [comment]
or read other people issues and try fix it from using there info

**Comment by pau101** [comment]
@EvilEclipse What mods do you have installed?

**Comment by pau101** [comment]
Some mods to change player rendering in a way not caring for other mod's attachments, so it is out of my control unfortunately.
